---
all:
  hosts:
    mn-coolify-cp:
      ansible_host: mn-prod-coolify-cp
      ansible_os_family: Debian
    mn-coolify-node1:
      ansible_host: mn-prod-coolify-sec-node1
      ansible_os_family: Debian
    mn-coolify-node2:
      ansible_host: mn-prod-coolify-int-node2
      ansible_os_family: Debian
    mn-coolify-node3:
      ansible_host: mn-prod-coolify-ext-node3
      ansible_os_family: Debian
    mn-coolify-node4:
      ansible_host: mn-prod-coolify-ext-node4
      ansible_os_family: Debian
  children:
    deb_srv:
      hosts:
        mn-coolify-cp:
        mn-coolify-node1:
        mn-coolify-node2:
        mn-coolify-node3:
        mn-coolify-node4:
